name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            install: choco install ninja
          - os: ubuntu-latest
            install: sudo apt install -yqq ninja-build
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make clean
      run: make clean
