name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: Debug
    strategy:
      fail-fast: true
      matrix:
        os: ubuntu-20.04
        cxx: clang++
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make clean
      run: make clean
